version: '3.8'

services:
  backend-dev:
    container_name: backend-dev
    build: ./
    ports:
    - 5000:5000
    environment:
      MONGO_URL: mongodb://root:secret@localhost:27017/todo-app-dev
      REDIS_URL: redis://localhost:6379
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
