version: '3.8'

services:
  frontend-dev:
    container_name: frontend-dev
    build: ./
    ports:
    - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:5000
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
