version: '3.8'

services:
  mongo-dev:
    container_name: mongo-dev
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: todo-app-dev
    volumes: 
      - ./services/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data-dev:/data/db
    restart: unless-stopped
  redis-dev:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  mongo-data-dev: