version: '3.8'

services:
  nginx-dev:
    container_name: nginx-dev
    image: nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend-dev
      - frontend-dev
    restart: unless-stopped
  frontend-dev:
    container_name: frontend-dev
    build: ./services/frontend
    ports:
    - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080/api/
    volumes:
      - ./services/frontend/:/usr/src/app
    depends_on:
      - backend-dev
    restart: unless-stopped
  backend-dev:
    container_name: backend-dev
    build: services/backend
    ports:
    - 5000:5000
    environment:
      MONGO_URL: mongodb://root:secret@mongo-dev:27017/todo-app-dev
      REDIS_URL: redis://redis-dev:6379
    depends_on:
      - mongo-dev
      - redis-dev
    volumes:
      - ./services/backend/:/usr/src/app
    restart: unless-stopped
  mongo-dev:
    container_name: mongo-dev
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: todo-app-dev
    volumes: 
      - ./services/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data-dev:/data/db
    restart: unless-stopped
  redis-dev:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data-dev:/data
    restart: unless-stopped

volumes:
  mongo-data-dev:
  redis-data-dev:
