version: '3.8'

services:
  backend-dev:
    container_name: backend-dev
    build: services/backend
    ports:
    - 5000:5000
    environment:
      MONGO_URL: mongodb://root:secret@mongo-dev:27017/todo-app-dev
      REDIS_URL: redis://redis-dev:6379
    depends_on:
      - mongo-dev
      - redis-dev
    volumes:
      - ./services/backend/:/usr/src/app
    restart: unless-stopped
  mongo-dev:
    container_name: mongo-dev
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: todo-app-dev
    volumes: 
      - ./services/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data-dev:/data/db
    restart: unless-stopped
  redis-dev:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data-dev:/data
    restart: unless-stopped

volumes:
  mongo-data-dev:
  redis-data-dev:
