version: '3.8'

services:
  redis-dev:
    container_name: redis-dev
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data-dev:/data
    restart: unless-stopped

volumes:
  redis-data-dev:
